//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRoomReserver.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Core.Objects.DataClasses;
    using System.Linq;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<rooms> rooms { get; set; }
        public DbSet<rowsReserve> rowsReserve { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<RBU_view> RBU_view { get; set; }
    
        public virtual ObjectResult<sp_RBU_Result> sp_RBU(Nullable<int> p_id)
        {
            var p_idParameter = p_id.HasValue ?
                new ObjectParameter("_id", p_id) :
                new ObjectParameter("_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RBU_Result>("sp_RBU", p_idParameter);
        }

        public System.Data.Entity.DbSet<UserRoomReserver.Models.sp_RBU_Result> sp_RBU_Result { get; set; }
    }
}
