//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRoomReserver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBU_view
    {
        public int id { get; set; }
        public int Expr1 { get; set; }
        public string fullName { get; set; }
        public string cc { get; set; }
        public string city { get; set; }
        public Nullable<System.DateTime> dateReserve { get; set; }
        public Nullable<int> numberPerson { get; set; }
        public string destinationReserve { get; set; }
        public Nullable<int> stateReserve { get; set; }
        public Nullable<int> idRoom { get; set; }
        public string roomName { get; set; }
    }
}
